environment:
  matrix:
    - nodejs_version: "4.7.2"
    - nodejs_version: "6"
platform:
  - x86
  - x64
install:
    - ps: Install-Product node $env:nodejs_version
test_script:
  - npm start
build: off

